[features]
seeds = false
skip-lint = false
[programs.localnet]
anchor_counter_program = "BNoJPjrAtDJNhynak4rYUtUbGytaSJrRKpdg6iHxgzbs"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/jonasxchen/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
